/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_content_delivery_bucket": "magpotluck-20230112002418-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-1",
    "aws_content_delivery_url": "https://d1r44njgk4og7u.cloudfront.net"
};


export default awsmobile;
